## bw_Cons.py
##
## Written by Matthew Egan
## Last Revised: 26th August 2013

## Window Sizes
WIDTH_THRESHOLD = 1280

WIDTH_LARGE = 1280
HEIGHT_LARGE = 720

## Miscellaneous
LRG_PADDING = 15
LRG_BTN_HEIGHT = 60

## Positions
ORIGIN = (0,0)
LRG_TITLE_POS = (250, 40)

## CenterX = (ScreenWidth - ImgWidth)/2
## Title screen buttons
LRG_LOGIN_POS = (445, 338)
LRG_CREATE_POS = (445, LRG_LOGIN_POS[1]+LRG_BTN_HEIGHT+LRG_PADDING)
LRG_LEADER_POS = (445, LRG_CREATE_POS[1]+LRG_BTN_HEIGHT+LRG_PADDING)
LRG_HELP_POS = (445, LRG_LEADER_POS[1]+LRG_BTN_HEIGHT+LRG_PADDING)
LRG_EXIT_POS = (445, LRG_HELP_POS[1]+LRG_BTN_HEIGHT+LRG_PADDING)

## Login screen positions
LRG_LOGIN_TITLE_POS = (451, 40)
LRG_LOGIN_USERNAME_POS = (545, LRG_LOGIN_POS[1]-LRG_BTN_HEIGHT-LRG_PADDING)
LRG_LOGIN_FIELD1_POS = (445, LRG_LOGIN_USERNAME_POS[1]+LRG_BTN_HEIGHT+LRG_PADDING)
LRG_LOGIN_PASSWORD_POS = (548, LRG_LOGIN_FIELD1_POS[1]+LRG_BTN_HEIGHT+LRG_PADDING)
LRG_LOGIN_FIELD2_POS = (445, LRG_LOGIN_PASSWORD_POS[1]+LRG_BTN_HEIGHT+LRG_PADDING)
LRG_LOGIN_CONFIRM_POS = (445, LRG_LOGIN_FIELD2_POS[1]+LRG_BTN_HEIGHT+LRG_PADDING)
LRG_LOGIN_EXIT_POS = (445, LRG_LOGIN_CONFIRM_POS[1]+LRG_BTN_HEIGHT+LRG_PADDING)
LRG_USERNAME_START_POS = (LRG_LOGIN_FIELD1_POS[0] + LRG_PADDING, LRG_LOGIN_FIELD1_POS[1] + LRG_BTN_HEIGHT - (0.5*LRG_PADDING))
LRG_PASSWORD_START_POS = (LRG_LOGIN_FIELD2_POS[0] + LRG_PADDING, LRG_LOGIN_FIELD2_POS[1] + LRG_BTN_HEIGHT - (0.5*LRG_PADDING))
LRG_TICKBOX = (LRG_LOGIN_FIELD2_POS[0]-102, LRG_LOGIN_FIELD2_POS[1])
LRG_CHK_AST = (LRG_TICKBOX[0] + 15, LRG_TICKBOX[1] + 15)

## Create Account positions
LRG_NEWUSER_TITLE_POS = (120, 54)

## Game screen positions
LRG_GAME_BAR = (ORIGIN[0], HEIGHT_LARGE-100)
LRG_GAME_TYPE = (ORIGIN[0]+10, HEIGHT_LARGE-90)
LRG_GAME_FIELD = (ORIGIN[0]+50+395, HEIGHT_LARGE-85)
LRG_GAME_CRTWORD = (LRG_LOGIN_PASSWORD_POS[0]-100, LRG_LOGIN_PASSWORD_POS[1] + 275)
LRG_GAME_CLOCK = (WIDTH_LARGE - 94-15, 15)

## Help screen positions
LRG_HELP_TITLE_POS = (495, LRG_LOGIN_TITLE_POS[1])
LRG_HELP_BODY_POS = (247, LRG_LOGIN_USERNAME_POS[1])
LRG_HELP_DONE_POS = LRG_LOGIN_CONFIRM_POS

## Store screen positions
LRG_STORE_BODY_POS = (247, LRG_LOGIN_USERNAME_POS[1]-40)
LRG_STORE_ATK_POS = (267, LRG_LOGIN_USERNAME_POS[1]+46)
LRG_STORE_ARR_POS = (267, LRG_LOGIN_USERNAME_POS[1]+(46*2)+15)
LRG_STORE_MAG_POS = (267, LRG_STORE_ARR_POS[1]+46+15)
LRG_PTNSLFT_POS = (700, LRG_STORE_ATK_POS[1])
LRG_ATK_PLS_POS = (600, LRG_STORE_ATK_POS[1])
LRG_ARR_PLS_POS = (600, LRG_STORE_ARR_POS[1])
LRG_MAG_PLS_POS = (600, LRG_STORE_MAG_POS[1])
LRG_STORE_DONE_POS = (LRG_HELP_DONE_POS[0], LRG_HELP_DONE_POS[1]-50)

## Leaderboard screen positions
LRG_LEADER_TITLE_POS = (178, 40)
LRG_LEADER_DAILY = (370, 222)
LRG_LEADER_ALLTIME = (807, 222)
LRG_LEADER_DUSER = (229, 300)
LRG_LEADER_DSCORE = (473, 300)
LRG_LEADER_DBAR = (200, 343)
LRG_LEADER_AUSER = (700, 300)
LRG_LEADER_ASCORE = (943, 300)
LRG_LEADER_ABAR = (670, 343)

# Screen Names
TITLE = "Title"
LOGIN = "Login"
NEWUSER = "NewUser"
HIGHSCORES = "HighScores"
HELP = "Help"
GAME = "Game"
EXITGAME = "Exit"
